NHL_TEAMS = {
    "Anaheim": "ducks",
    "Boston": "bruins",
    "Buffalo": "sabres",
    "Calgary": "flames",
    "Carolina": "hurricanes",
    "Chicago": "blackhawks",
    "Colorado": "avalanche",
    "Columbus": "bluejackets",
    "Dallas": "stars",
    "Detroit": "redwings",
    "Edmonton": "oilers",
    "Florida": "panthers",
    "Los Angeles": "kings",
    "Minnesota": "wild",
    "Montreal": "canadiens",
    "Nashville": "predators",
    "New Jersey": "devils",
    "NY Islanders": "islanders",
    "NY Rangers": "rangers",
    "Ottawa": "senators",
    "Philadelphia": "flyers",
    "Pittsburgh": "penguins",
    "San Jose": "sharks",
    "Seattle": "kraken",
    "St. Louis": "blues",
    "Tampa Bay": "lightning",
    "Toronto": "mapleleafs",
    "Utah": "utah",  # to be changed when Utah team is announced
    "Vancouver": "canucks",
    "Vegas": "goldenknights",
    "Washington": "capitals",
    "Winnipeg": "jets",
}
