NHL_TEAMS = {
    "Anaheim": "ducks",
    "Boston": "bruins",
    "Buffalo": "sabres",
    "Calgary": "flames",
    "Carolina": "hurricanes",
    "Chicago": "blackhawks",
    "Colorado": "avalanche",
    "Columbus": "bluejackets",
    "Dallas": "stars",
    "Detroit": "redwings",
    "Edmonton": "oilers",
    "Florida": "panthers",
    "Los Angeles": "kings",
    "Minnesota": "wild",
    "Montreal": "canadiens",
    "Nashville": "predators",
    "New Jersey": "devils",
    "NY Islanders": "islanders",
    "NY Rangers": "rangers",
    "Ottawa": "senators",
    "Philadelphia": "flyers",
    "Pittsburgh": "penguins",
    "San Jose": "sharks",
    "Seattle": "kraken",
    "St. Louis": "blues",
    "Tampa Bay": "lightning",
    "Toronto": "mapleleafs",
    "Utah": "utah",  # to be changed when Utah team is announced
    "Vancouver": "canucks",
    "Vegas": "goldenknights",
    "Washington": "capitals",
    "Winnipeg": "jets",
}
NHL_TEAMS_FOR_DRAFT = {
    "ANA": "Anaheim",
    "ATL": "Atlanta",
    "ARI": "Arizona",
    "BOS": "Boston",
    "BUF": "Buffalo",
    "CAR": "Carolina",
    "CBJ": "Columbus",
    "CGY": "Calgary",
    "CHI": "Chicago",
    "COL": "Colorado",
    "DAL": "Dallas",
    "DET": "Detroit",
    "EDM": "Edmonton",
    "FLA": "Florida",
    "LAK": "Los Angeles",
    "MIN": "Minnesota",
    "MTL": "Montreal",
    "NJD": "New Jersey",
    "NSH": "Nashville",
    "NYI": "NY Islanders",
    "NYR": "NY Rangers",
    "OTT": "Ottawa",
    "PHI": "Philadelphia",
    "PIT": "Pittsburgh",
    "SJS": "San Jose",
    "STL": "St. Louis",
    "TBL": "Tampa Bay",
    "TOR": "Toronto",
    "UTA": "Utah",
    "VAN": "Vancouver",
    "VGK": "Vegas",
    "WPG": "Winnipeg",
    "WSH": "Washington",
}
